spring:
  application:
    name: AUTH-SERVICE
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/teste
    username: root
    password: thalleshenrique
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

server:
  port: 8302
  
eureka:
  instance:
    appname: AUTH-SERVICE
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:5541/eureka

ribbon:
  eureka:
    enabled: true