spring:
  application:
    name: eureka-service

server:
  port: 5541

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://localhost:5541/eureka
  server:
    waitTimeInMsWhenSyncEmpty: 0
    
zuul:
  prefix: /api
  routes:
    auth-service:
      path: /auth/**
      serviceId: auth-service
      strip-prefix: false
      sensitive-headers: Cookie,Set-Cookie
    db-service:
      path: /db-service/**
      serviceId: db-service
    stock-service:
      path: /stock-service/**
      serviceId: stock-service
            

auth-service:
  ribbon:
    NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList
    listOfServers: localhost:8302
    ConnectTimeout: 1000
    ReadTimeout: 3000
    MaxTotalHttpConnections: 500
    MaxConnectionsPerHost: 100
     
      